#Crunchyroll Downloader NX configuration v3
bin:
  ffmpeg: ${__dirname}/bin/ffmpeg
  mkvmerge: ${__dirname}/bin/mkvmerge
dir:
  fonts: ${__dirname}/fonts/
  content: ${__dirname}/videos/
  trash: ${__dirname}/videos/_trash/
cli:
  releaseGroup: CR
  fileSuffix: SIZEp
  videoQuality: 720p
  dubLanguage: jpn
  mp4mux: false
  muxSubs: false
  noCleanUp: false
  nServer: 1
  oldSubs: false
  dlSubs: all
#eof
