#Crunchyroll Downloader NX configuration v2
bin:
  ffmpeg: ${__dirname}/modules/ffmpeg
  mkvmerge: ${__dirname}/modules/mkvtoolnix/mkvmerge
dir:
  content: ${__dirname}/videos/
  trash: ${__dirname}/videos/_trash/
cli:
  releaseGroup: CR
  fileSuffix: SIZEp
  videoQuality: 720p
  dubLanguage: jpn
  mp4mux: false
  muxSubs: false
  noCleanUp: false
  nServer: 1
  oldSubs: false
  dlSubs: all
#eof
